// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBB5WgxDypFr2U-AT8isgk6Gp8Ttla7YZ8',
    appId: '1:940405754676:web:969c3b84186d9ec3027361',
    messagingSenderId: '940405754676',
    projectId: 'campusconnect-beb93',
    authDomain: 'campusconnect-beb93.firebaseapp.com',
    storageBucket: 'campusconnect-beb93.appspot.com',
    measurementId: 'G-3GV5VMKT28',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBqikbOvxHhJ3cJeLuUci52mNqO64ZRNsM',
    appId: '1:940405754676:android:1c18f4a605f781a6027361',
    messagingSenderId: '940405754676',
    projectId: 'campusconnect-beb93',
    storageBucket: 'campusconnect-beb93.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCmFjvFlfnEtXpw0roo3r4A6U5_39Cs_No',
    appId: '1:940405754676:ios:c6cd48dc2af34eaa027361',
    messagingSenderId: '940405754676',
    projectId: 'campusconnect-beb93',
    storageBucket: 'campusconnect-beb93.appspot.com',
    iosBundleId: 'com.example.campusconnect',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCmFjvFlfnEtXpw0roo3r4A6U5_39Cs_No',
    appId: '1:940405754676:ios:c6cd48dc2af34eaa027361',
    messagingSenderId: '940405754676',
    projectId: 'campusconnect-beb93',
    storageBucket: 'campusconnect-beb93.appspot.com',
    iosBundleId: 'com.example.campusconnect',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBB5WgxDypFr2U-AT8isgk6Gp8Ttla7YZ8',
    appId: '1:940405754676:web:ff5a58f9587e36ed027361',
    messagingSenderId: '940405754676',
    projectId: 'campusconnect-beb93',
    authDomain: 'campusconnect-beb93.firebaseapp.com',
    storageBucket: 'campusconnect-beb93.appspot.com',
    measurementId: 'G-WT4MS5H973',
  );

}